package com.compiler.lexer;

public enum TokenType {
    INT_LIT, FLOAT_LIT, STRING_LIT, BOOL_LIT,
    IDENT,
    WHILE, FOR, IN, RANGE, PRINT,
    DEF, RETURN, IMPORT, FROM, AS,
    PLUS, MINUS, STAR, SLASH, MOD,
    EQ, NEQ, LT, LE, GT, GE,
    IF, ELIF, ELSE,
    ASSIGN, PLUS_ASSIGN, MINUS_ASSIGN,
    LPAREN, RPAREN, LBRACKET, RBRACKET,
    COMMA, COLON, DOT,
    NEWLINE, INDENT, DEDENT,
    EOF, UNKNOWN
}